django_project/admin_app/urls.py
from django.urls import path
from . import views


app_name = 'admin_app'


urlpatterns = [
    path('', views.UserList.as_view(), name='user_list'),
    path('detail/<int:pk>', views.UserDetail.as_view(), name='user_detail'),
    path('create', views.UserCreate.as_view(), name='user_create'),
    path('update/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
    path('delete/<int:pk>', views.UserDelete.as_view(), name='user_delete'),
]

django_project/auth_app/urls.py
from django.urls import path
from . import views


app_name = 'auth_app'


urlpatterns = [
    path('signin', views.SignIn.as_view(), name='sign_in'),
    path('signout', views.sign_out, name='sign_out'),
]

django_project/collections_app/urls.py
from django.urls import path
from . import views

app_name = 'collections_app'


urlpatterns = [
    path('', views.CollectionView.as_view(), name='collection'),
    path('interiors', views.InteriorView.as_view(), name='interior'),
    path('<str:name>', views.WallpaperView.as_view(), name='wallpaper'),
]

django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from auth_app import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from sitetree.sitetreeapp import register_i18n_trees

register_i18n_trees(['website', ])

urlpatterns = [
    path('', include('main_app.urls', namespace='main')),
    path('auth/', include('auth_app.urls', namespace='auth')),
    path('register/', auth_views.Registration.as_view(), name='register'),
    path('admin_panel/', include('admin_app.urls', namespace='admin_panel')),
    path('admin/', admin.site.urls),
    path('collections/', include('collections_app.urls', namespace='collections'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/templates/base.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% load sitetree%}
{% load static %}
<script src="{% bootstrap_jquery_url %}"></script>
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    {% block head %}
    {% endblock %}
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Главная страница</a>
          <a class="navbar-brand" href="{% url 'collections_app:collection' %}">Коллекции</a>
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'admin_panel:user_list' %}">Администрирование</a>
            {% endif %}
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>  {{ user.username }}</a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'admin_panel:user_detail' user.id %}">Профиль</a></li>
                        <li><a href="{% url 'auth:sign_out' %}">Выход</a></li>
                    </ul>
                </li>
            {% else %}
                <li><a href="{% url 'auth:sign_in' %}">Авторизация</a></li>
                <li><a href="{% url 'register' %}">Регоистрация</a></li>
            {% endif %}
          </ul>

          <!--<form class="navbar-form navbar-right">-->
            <!--<input type="text" class="form-control" placeholder="Search...">-->
          <!--</form>-->
        </div>
      </div>
    </div>
    <div class="container">
        {% sitetree_breadcrumbs from "website" template "sitetree/breadcrumbs_bootstrap3.html" %}

        {% block container %}
        {% endblock %}
    </div>
<div>
    {% block footer %}
    {% endblock %}
</div>
</body>
</html>