django_project/auth_app/urls.py
from django.urls import path
from . import views


app_name = 'auth_app'


urlpatterns = [
    path('signin', views.SignIn.as_view(), name='sign_in'),
    path('signout', views.sign_out, name='sign_out'),
]

django_project/collections_app/urls.py
from django.urls import path
from . import views

app_name = 'collections_app'


urlpatterns = [
    path('', views.CollectionView.as_view(), name='collection'),
    path('interiors', views.InteriorView.as_view(), name='interior'),
    path('<str:name>', views.WallpaperView.as_view(), name='wallpaper'),
]

django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from auth_app import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from sitetree.sitetreeapp import register_i18n_trees

register_i18n_trees(['website', ])

urlpatterns = [
    path('', include('main_app.urls', namespace='main')),
    path('auth/', include('auth_app.urls', namespace='auth')),
    path('register/', auth_views.Registration.as_view(), name='register'),
    path('admin_panel/', include('admin_app.urls', namespace='admin_panel')),
    path('admin/', admin.site.urls),
    path('collections/', include('collections_app.urls', namespace='collections'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/collections_app/models.py
from django.db import models

# Create your models here.


class Collection(models.Model):
    name = models.CharField(max_length=128, unique=True)
    img = models.ImageField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name.replace(" ", "_")


class Wallpaper(models.Model):
    article = models.CharField(max_length=32, unique=True)
    description = models.TextField(null=True, blank=True)
    preview_img = models.ImageField()
    img = models.ImageField(null=True, blank=True)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE, null=True, blank=True)
    rapport = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    class Meta:
        ordering = ["article"]

    def __str__(self):
        return str(self.article)


class Interior(models.Model):
    name = models.CharField(max_length=128)
    img = models.ImageField()

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

django_project/collections_app/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
from django.views.generic import TemplateView
from django.views.generic import ListView, DetailView
from django.views import View
from .models import Wallpaper, Interior, Collection


class InteriorView(View):
    template_name = 'collections_app/interiors.html'
    interiors = Interior.objects.all()
    collections = Collection.objects.all()

    def get(self, request, *args, **kwargs):
        collection_name = request.GET.get('collection_name', None)
        # preview_collection = request.META.get('HTTP_REFERER').split('/')[4]
        if collection_name:
            wallpapers = list(Wallpaper.objects.filter(collection__name=collection_name).values())
            return JsonResponse(wallpapers, safe=False)
        wallpapers = Wallpaper.objects.filter(collection__name=self.collections[0].name)
        context = {'wallpapers': wallpapers,
                   'interiors': self.interiors,
                   'collections': self.collections}
        return render(request, self.template_name, context)

    # def get_queryset(self):
    #     if self.request.user.is_superuser:
    #         return self.model.objects.all()
    #     return self.model.objects.exclude(Q(is_superuser=True) | Q(is_staff=True))


class CollectionView(TemplateView):
    template_name = 'collections_app/collections.html'

    def get(self, request, *args, **kwargs):
        collections = Collection.objects.all()
        context = {'collections': collections}
        return render(request, self.template_name, context)


class WallpaperView(View):
    template_name = 'collections_app/wallpapers.html'

    def get(self, request, name, *args, **kwargs):
        name = name.replace('_', ' ')
        collection = Collection.objects.get(name=name) # получаем необходимую коллекцию для предпросмотра
        context = {'collection': collection}
        return render(request, self.template_name, context)

django_project/collections_app/templates/collections_app/carousel_collection.html
<div class="item row col-xs-4 col-sm-4 col-md-3" id="collection_carousel_conteiner">
    <ul id="collection-slider" class="content-slider">
        {% for collection in collections %}
        <li id="{{ forloop.counter }}">
            <button class="btn-link" type="button" id="{{ collection }}">
                <img src="/media/{{ collection.img }}" alt="изображение не найдено" class="img-responsive">
                <b>{{ collection.name }}</b>
            </button>
        </li>
        {% endfor %}
    </ul>
</div>

django_project/collections_app/templates/collections_app/carousel_interior.html
<div class="item" id="interior_carousel_conteiner">
    <ul id="interior-slider" class="content-slider">
        {% for interior in interiors %}
        <li>
            <button type="button" class="room btn-link">
                <img src="/media/{{ interior.img }}" alt="изображение не найдено" class="img-responsive">
            </button>
        </li>
        {% endfor %}
    </ul>
</div>

django_project/collections_app/templates/collections_app/carousel_wollpaper.html
<div class="item row col-xs-offset-4 col-sm-offset-4 col-md-offset-3" id="wallpaper_carousel_conteiner">
    <ul id="wallpaper-slider" class="content-slider">
        {% for wallpaper in wallpapers %}
        <li>
            <button type="button" class="wall btn-link">
                <img src="/media/{{ wallpaper.preview_img }}" alt="..." class="img-responsive" data-rapport="{{ wallpaper.rapport }}">
            </button>
            <p>{{ wallpaper.article }}</p>
        </li>
        {% endfor %}
    </ul>
</div>

django_project/collections_app/templates/collections_app/collections.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/collection.css' %}" />
{% endblock %}
{% block title %}collections{% endblock %}
{% block container %}
<div class="image_block">
    <h1>Collections</h1>
    <br/>
    <div class="list-group">
        {% for collection in collections %}
        <div class="collection">
            <a href="{% url 'collections:wallpaper' collection %}">
                <img src="/media/{{ collection.img }}" alt="изображение не найдено" class="img-responsive img_collection">
                <p>{{ collection.name }}</p>
            </a>
        </div>
        {% endfor %}
    </div>

    <a href="{% url 'collections:interior' %}">
        <h4>Смотреть в интерьере</h4>
    </a>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

{% endblock %}

django_project/collections_app/templates/collections_app/interiors.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/collection.css' %}" />
<link rel="stylesheet" href="{% static 'css/lightslider.min.css' %}" />
{% endblock %}
{% block title %}interiors{% endblock %}
{% block container %}
<div class="image_block">
    <div class="col-md-2 col-xs-2">
        <!-- слайдер для интерьеров -->
        {% include "collections_app/carousel_interior.html" %}
    </div>
    <div class="col-md-10 col-xs-10 interior-container">
        <!-- canvas -->
        <div class="img-rounded">
            <img src="/media/interior1.png" id="pic_interior">
        </div>
        <div class="img-rounded" id="canvas_container">
            <canvas id="canvas_interior"></canvas>
        </div>
        <!-- слайдер для колекций -->
        {% include "collections_app/carousel_collection.html" %}
        <!-- слайдер для обоев -->
        {% include "collections_app/carousel_wollpaper.html" %}
    </div>
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="{% static 'js/lightslider.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/my_js.js' %}"></script>
{% endblock %}

django_project/collections_app/templates/collections_app/wallpapers.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/collection.css' %}" />
<link rel="stylesheet" href="{% static 'css/lightslider.min.css' %}" />
{% endblock %}
{% block title %}wallpaprs{% endblock %}
{% block container %}
<div id="current_collection">
    <h1>{{ collection.name }}</h1>
    <br/>
    <a href="{% url 'collections:interior' %}">
        смотреть в интерьере
    </a>
</div>


<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

{% endblock %}