django_project/admin_app/urls.py
from django.urls import path
from . import views


app_name = 'admin_app'


urlpatterns = [
    path('', views.UserList.as_view(), name='user_list'),
    path('detail/<int:pk>', views.UserDetail.as_view(), name='user_detail'),
    path('create', views.UserCreate.as_view(), name='user_create'),
    path('update/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
    path('delete/<int:pk>', views.UserDelete.as_view(), name='user_delete'),
]

django_project/auth_app/urls.py
from django.urls import path
from . import views


app_name = 'auth_app'


urlpatterns = [
    path('signin', views.SignIn.as_view(), name='sign_in'),
    path('signout', views.sign_out, name='sign_out'),
]

django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from auth_app import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from sitetree.sitetreeapp import register_i18n_trees

register_i18n_trees(['website', ])

urlpatterns = [
    path('', include('main_app.urls', namespace='main')),
    path('auth/', include('auth_app.urls', namespace='auth')),
    path('register/', auth_views.Registration.as_view(), name='register'),
    path('admin_panel/', include('admin_app.urls', namespace='admin_panel')),
    path('admin/', admin.site.urls),
    path('collections/', include('collections_app.urls', namespace='collections'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/admin_app/models.py
from django.db import models

# Create your models here.

django_project/admin_app/forms.py
from django import forms
from django.contrib.auth import get_user_model
import re
from django.contrib.auth.forms import UserChangeForm


class CreateUserForm(forms.ModelForm):
    fio = forms.CharField(label='ФИО', widget=forms.TextInput(attrs={}))
    email = forms.CharField(label='Email', widget=forms.EmailInput())
    username = forms.CharField(label='Имя пользователя')
    is_active = forms.CharField(label='Активный', widget=forms.CheckboxInput)
    is_staff = forms.CharField(label='Администратор', widget=forms.CheckboxInput)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ('fio', 'email', 'username', 'is_active', 'is_staff', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'is_active' or field_name == 'is_staff':
                field.widget.attrs['class'] = 'form-check-input'
            field.required = False
            field.help_text = ''

    def clean_fio(self):
        '''Определяем правило валидации поля FIO'''
        fio = self.cleaned_data.get('fio')
        fio = str(fio).split(' ')
        if len(fio) != 3: # проверяет количество слов
            raise forms.ValidationError('Недостаточно данных!')
        else:
            for string in fio:
                if not re.match(r'^[A-Za-zА-Яа-я]*$', string): # проверяет на соответствие регулярному выражению
                    raise forms.ValidationError('Текст должен содержать только буквы!')
        fio_dict = {
            'first_name': fio[1],
            'lastname': fio[0],
            'surname': fio[2]
        }
        return fio_dict

    def clean_confirm_password(self):
        '''валидация пароля'''
        password = self.cleaned_data.get('password')
        conf_password = self.cleaned_data.get('confirm_password')
        if password or conf_password:
            if password != conf_password:
                raise forms.ValidationError('Пароли не совпадают!')
            else:
                if not re.match(r'^(?=.*[0-9].*)(?=.*[a-z].*)(?=.*[A-Z].*)[0-9a-zA-Z]{8,}$', password):
                    raise forms.ValidationError('Пароль должен содержать не менее 8 симвоолов, буквы \
                    верхнего и нижнего регистра и цифры!')
        else:
            raise forms.ValidationError('Поле пароля пустое!')
        return self.cleaned_data['confirm_password']


class UpdateUserForm(forms.ModelForm):
    fio = forms.CharField(label='ФИО', widget=forms.TextInput(attrs={}))
    email = forms.CharField(label='Email', widget=forms.EmailInput())
    username = forms.CharField(label='Имя пользователя')
    is_active = forms.CharField(label='Активный', widget=forms.CheckboxInput)
    is_staff = forms.CharField(label='Администратор', widget=forms.CheckboxInput)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ('fio', 'email', 'is_active', 'is_staff')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'is_active' or field_name == 'is_staff':
                field.widget.attrs['class'] = 'form-check-input'
            field.required = False
            field.help_text = ''

    def clean_fio(self):
        '''Определяем правило валидации поля FIO'''
        fio = self.cleaned_data.get('fio')
        fio = str(fio).split(' ')
        if len(fio) != 3: # проверяет количество слов
            raise forms.ValidationError('Недостаточно данных!')
        else:
            for string in fio:
                if not re.match(r'^[A-Za-zА-Яа-я]*$', string): # проверяет на соответствие регулярному выражению
                    raise forms.ValidationError('Текст должен содержать только буквы!')
        fio_dict = {
            'first_name': fio[1],
            'lastname': fio[0],
            'surname': fio[2]
        }
        return fio_dict

    def clean_username(self):
        '''переопределяем валидацию username'''
        username = self.cleaned_data.get('username')
        if get_user_model().objects.filter(username=username).exists():
            return self.cleaned_data['username']
        return self.cleaned_data['username']

    def clean_confirm_password(self):
        '''валидация пароля'''
        password = self.cleaned_data.get('password')
        conf_password = self.cleaned_data.get('confirm_password')
        if password:
            if password != conf_password:
                raise forms.ValidationError('Пароли не совпадают!')
            else:
                if not re.match(r'^(?=.*[0-9].*)(?=.*[a-z].*)(?=.*[A-Z].*)[0-9a-zA-Z]{8,}$', password):
                    raise forms.ValidationError('Пароль должен содержать не менее 8 симвоолов, буквы \
                    верхнего и нижнего регистра и цифры!')
        return self.cleaned_data['confirm_password']

    def delete_fields(self):
        del self.fields['is_active']
        del self.fields['is_staff']

django_project/admin_app/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.views.generic import ListView, DetailView
from .forms import CreateUserForm, UpdateUserForm
from django.views import View
from .decorators import SuperuserRequiredMixin
from pprint import pprint
from django.db.models import Q


class UserList(SuperuserRequiredMixin, ListView):
    '''список пользователей(администраторов)'''
    model = get_user_model()
    template_name = 'admin_app/user_list.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return self.model.objects.all()
        return self.model.objects.exclude(Q(is_superuser=True) | Q(is_staff=True))


class UserDetail(SuperuserRequiredMixin, DetailView):
    '''поисание пользователя и опции'''
    model = get_user_model()
    template_name = 'admin_app/user_detail.html'


class UserCreate(SuperuserRequiredMixin, View):
    '''создание нового пользователя'''
    title = 'создать'
    initial = {'is_active': True}
    form_class = CreateUserForm
    template_name = 'admin_app/user_create_update.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form, 'title': self.title})

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            fio = form.cleaned_data.pop('fio', '') # удаляем ключ fio и получаем его значение
            new_user = form.save()
            get_user_model().objects.filter(id=new_user.id).update(**fio)
            return HttpResponseRedirect(reverse('admin_panel:user_detail', args=(new_user.id, )))
        return render(request, self.template_name, {'form': form, 'title': self.title})


class UserUpdate(SuperuserRequiredMixin, View):
    title = 'обновить'
    template_name = 'admin_app/user_create_update.html'
    form_class = UpdateUserForm

    def get(self, request, pk, *args, **kwargs):
        user = get_object_or_404(get_user_model(), pk=pk)
        form = self.form_class(initial=self.create_initial_dict(user))
        if user.is_superuser: # если выбранный пользователь superuser
            form.delete_fields() # удалить поля is_active и is_staff
        context = {'form': form,
                   'title': self.title,
                   'object': user}
        return render(request, self.template_name, context)

    def post(self, request, pk, *args, **kwargs):
        user = get_object_or_404(get_user_model(), pk=pk)
        form = self.form_class(request.POST, request.FILES)
        if user.is_superuser: # если выбранный пользователь superuser
            form.delete_fields() # удалить поля is_active и is_staff
        if form.has_changed() and form.is_valid():
            fio = form.cleaned_data.pop('fio', '') # удаляем ключ fio и получаем его значение
            data = {**form.cleaned_data, **fio}
            changed_data = data.copy() # создаем копию словаря которую будем изменять
            for key, val in data.items(): # обходим словарь в цикле
                if val == '' or key == 'confirm_password' or key == 'password':
                    changed_data.pop(key, None) # в созданной копии словаря вносим изменения
            get_user_model().objects.filter(pk=pk).update(**changed_data)
            if data['password']: # если пароль указан
                user.set_password(data['password']) # тогда обновить пароль
                user.save() # сохраняем внесенные изменения
            return HttpResponseRedirect(reverse('admin_panel:user_detail', args=(user.id,)))
        return render(request, self.template_name, {'form': form, 'title': self.title, 'object': user})

    def create_initial_dict(self, instance):
        '''создает словарь для инициализации полей формы при обновлении'''
        instance_dict = {
            'fio': '{} {} {}'.format(instance.lastname,
                                     instance.first_name,
                                     instance.surname),
            'email': instance.email,
            'username': instance.username,
            'is_active': instance.is_active,
            'is_staff': instance.is_staff
        }
        return instance_dict


class UserDelete(SuperuserRequiredMixin, View):
    template_name = 'admin_app/delete_confirmation.html'

    def get(self, request, pk, *args, **kwargs):
        user = get_object_or_404(get_user_model(), pk=pk)
        context = {'object': user}
        return render(request, self.template_name, context)

    def post(self, request, pk, *args, **kwargs):
        '''удаление пользователя'''
        user = get_object_or_404(get_user_model(), pk=pk)
        user.delete()
        # user.is_active = False
        # user.save()
        return HttpResponseRedirect(reverse('admin_panel:user_list'))

django_project/admin_app/templates/admin_app/delete_confirmation.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block title %}{{ title }}{% endblock %}
{% block container %}

<h2>Панель администратора</h2>
<div class="alert alert-danger" role="alert">
  <strong>Вы уверены, что хотите удалить пользователя {{ object.username }}</strong>
</div>
<form  method="post" class="form-signin panel" role="form" action="{% url 'admin_panel:user_delete' object.id %}">
    {% csrf_token %}
    <button class="btn btn-lg btn-danger btn-block" type="submit">Удалить</button>
</form>
<div class="panel">
    <a href="{% url 'admin_panel:user_detail' object.id %}" class="btn btn-lg btn-primary btn-block">Отмена</a>
</div>

{% endblock %}

django_project/admin_app/templates/admin_app/user_create_update.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
{% endblock %}
{% block title %}{{ title }}{% endblock %}
{% block container %}

<h2>Панель администратора</h2>
<form  method="post" class="form-signin" role="form">
    {% csrf_token %}
    <div>
        {% for field in form %}
        <div class="form-group">
        <p>{{field.label_tag}} {{field}}</p>
            {% if field.errors%}
            {% for error in field.errors %}
        <div class="alert alert-danger">
            {{error}}
        </div>
            {% endfor %}
            {% endif %}
        </div>
        {% endfor %}
    </div><br/>
    <button class="btn btn-lg btn-primary btn-block" type="submit">{{ title }}</button>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/double_email.js' %}"></script>

{% endblock %}

django_project/admin_app/templates/admin_app/user_detail.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block title %}edit{% endblock %}
{% block container %}

<h2>Панель администратора</h2>
<div class="panel panel-default">
    <div class="panel-heading">Информация о пользователе</div>
    <ul class="list-group">
        <li class="list-group-item"><b>ФИО:</b> {{ object.lastname }} {{ object.first_name }} {{ object.surname }}</li>
        <li class="list-group-item"><b>Имя пользователя:</b> {{ object.username }}</li>
        <li class="list-group-item"><b>E-mail:</b> {{ object.email }}</li>
    </ul>
</div>
<div class="panel">
    <a href="{% url 'admin_panel:user_update' object.id %}" class="btn btn-lg btn-primary btn-block">Обновить</a>
</div>
{% if user.id != object.id %}
    <div class="panel">
        <a href="{% url 'admin_panel:user_delete' object.id %}" class="btn btn-lg btn-danger btn-block">Удалить</a>
    </div>
{% endif %}

{% endblock %}

django_project/admin_app/templates/admin_app/user_list.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block title %}admin_panel{% endblock %}
{% block container %}

<h2>Панель администратора</h2>
<div class="panel panel-default">
    <div class="panel-heading">Список пользователей</div>
    {% for user in object_list %}
        <a href="{% url 'admin_panel:user_detail' user.id %}" class="list-group-item">{{ user.username }}</a>
    {% endfor %}
</div>
<div class="panel">
    <a href="{% url 'admin_panel:user_create' %}" class="btn btn-lg btn-primary btn-block">Создать</a>
</div>

{% endblock %}